# -*- coding: utf-8 -*-
"""student_form.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nBZ0FNLjbXUfNko15qJHBmi6awfBLsgr
"""




import streamlit as st
import openpyxl
import os

st.title("🎓 Student Registration Form")

# Create Excel file if not exists
excel_file = "student_data.xlsx"
if not os.path.exists(excel_file):
    workbook = openpyxl.Workbook()
    sheet = workbook.active
    sheet.title = "Data"
    sheet.append(["Name", "Gender", "Education"])
    workbook.save(excel_file)

# Form inputs
name = st.text_input("Name")
gender = st.radio("Gender", ["Male", "Female"])
education = st.selectbox("Education", ["Undergraduate", "Postgraduate", "Higher Education"])

if st.button("Submit"):
    if name == "":
        st.warning("Please enter a name.")
    else:
        # Save to Excel
        workbook = openpyxl.load_workbook(excel_file)
        sheet = workbook["Data"]
        sheet.append([name, gender, education])
        workbook.save(excel_file)
        st.success(f"✅ Data saved for {name}")


